image: registry.forge.orange-labs.fr/org.eclipse.om2m/om2m/com.orange.om2m.docker.builder:0.0.5

cache:
  paths:
    - .m2

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script: 
    - "nohup dockerd&"
    - "mvn clean install -Dmaven.repo.local=./.m2/repository -B -s /root/.m2/settings.xml"
  tags:
    - docker-privileged
    - rsc
    - shared
    
deploy:
  stage: deploy
  script: 
    - "nohup dockerd&"
    - "mvn deploy -B -Dmaven.repo.local=./.m2/repository -s /root/.m2/settings.xml -DaltDeploymentRepository=inhouse.snapshot::default::http://maven2.rd.francetelecom.fr/proxy/repository/inhouse.snapshot -Pdocker"
    - "rm -fr .m2"
  tags:
    - docker-privileged
    - rsc
    - shared
